### ISSUE TITLE
Account Controller Error

### ISSUE THREAD

**Issue by vpsantow** [wingblaze/ggms#5] opened 2016-03-17 12:54 UTC
`ErrorException in AccountController.php line 206:
Trying to get property of non-object`

 Error executed when accessed by all users

**Comment by wingblaze** [comment] 2016-03-18 03:56
Cannot reproduce error. Please give more details on how to reproduce issue.

Also, please make sure that the database is updated.
1. Drop the tables in the database (disable FK checks)
2. Use command line and go to the folder `cd git/ggms`
3. Create the tables (migrate) and populate them (seed) `php artisan migrate --seed`

**Comment by vpsantow** [comment] 2016-03-18 09:24
After failed attempts on pulling data, I noticed I got a lot of conflicting files so I cloned a new copy of the ggms folder(deleted original as well). Pull successful and said to be up to date stated by GitShell however I cant host server (php artisan serve via cmd) 

![image](https://cloud.githubusercontent.com/assets/17693687/13873632/abf53158-ed2d-11e5-8af6-1150a4ff0d47.png)

I've found a similar problem in this link[link](http://stackoverflow.com/questions/18406096/autoload-error-no-such-file-or-directory), although I cant seem to get it after numerous tries on adding/editing line 17 for "autoload" in relation to "C:\xampp\php\PEAR"

**Comment by wingblaze** [comment] 2016-03-20 07:14
What it's saying is it is looking for a file at

`C:\Users\Victor\Documents\GitHub\ggms\bootstrap/../vendor/autoload.php`

But it couldn't find the file. Please do the following:
1. Look for the `autoload.php` file in the ggms folder
2. Copy it to the folder directory where it is trying to find it in.

I think the folder it is looking in this one:

`C:\Users\Victor\Documents\GitHub\ggms\vendor\autoload.php`

But I am not sure. The two `/../` in the file path supposedly means the parent directory. Please let me know if this fixes it.

**Comment by vpsantow** [comment] 2016-03-20 08:51
I've tried replacing the suggested file location you posted and the file location of "autoload.php" which is `C:\Users\Victor\Documents\GitHub\ggms\bootstrap.` Still no avail same error

**Comment by wingblaze** [comment] 2016-03-20 15:22
When I checked your PC, the problem wasn't the `autoload.php` anymore and was instead the access permissions. It said `''@localhost not allowed...` or something to that effect, which made me doubt the configuration of the `.env` or the environment file.

Fixed. The filename should be empty, and the filetype should be `.env`.

Please close this issue if it is finished.

**Closed as completed** 2016-03-20 15:39 UTC
Labels: help wanted
